Fix Indexing Error For Multiline Files

diff --git a/chubby b/chubby
--- a/chubby
+++ b/chubby
@@ -119,7 +119,7 @@ function execute_line() {
     if [ $? -eq 0 ]; then
       echo "Success: $@"
     else
-      echo "Error: $@"
+      echo "Error $?: $@"
     fi
   fi
 }
@@ -149,8 +149,9 @@ function execute_file() {
   local wc=$(wc -l $file_path)
   local lines=${wc%% *}
 
-  for ((i=1; i<=$lines; i++)); do
-    execute_line $(sed -n "$(echo $i)p" $file_path)
+  for (( efi=1; efi<=$lines; efi++ )); do
+    local line=$(sed -n "$(echo $efi)p" $file_path)
+    execute_line $line
   done
 }
 
